/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue"
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffddb7",
        "tertiary-container": "#794c00",
        "outline": "#737781",
        "on-secondary-fixed": "#061c36",
        "on-surface-variant": "#434750",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#f9bb6b",
        "surface-bright": "#f7f9fc",
        "secondary-container": "#c7dbfe",
        "on-primary-fixed": "#001b3c",
        "surface-tint": "#385f97",
        "surface-dim": "#d8dadd",
        "error": "#ba1a1a",
        "on-tertiary-container": "#ffbf6f",
        "secondary-fixed": "#d4e3ff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#4d607d",
        "tertiary": "#5a3700",
        "on-tertiary-fixed-variant": "#653e00",
        "inverse-surface": "#2d3133",
        "on-tertiary": "#ffffff",
        "primary-container": "#2e568e",
        "on-error-container": "#93000a",
        "surface-container": "#eceef1",
        "secondary": "#4c5f7d",
        "primary": "#0f3e75",
        "on-primary-container": "#afccff",
        "surface-container-highest": "#e0e3e6",
        "primary-fixed-dim": "#a8c8ff",
        "on-surface": "#191c1e",
        "on-background": "#191c1e",
        "inverse-primary": "#a8c8ff",
        "surface-container-high": "#e6e8eb",
        "surface-variant": "#e0e3e6",
        "on-primary-fixed-variant": "#1c477e",
        "on-error": "#ffffff",
        "surface-container-low": "#f2f4f7",
        "secondary-fixed-dim": "#b4c8e9",
        "primary-fixed": "#d5e3ff",
        "on-secondary-fixed-variant": "#354864",
        "surface": "#f7f9fc",
        "background": "#f7f9fc",
        "outline-variant": "#c3c6d1",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#eff1f4",
        "on-tertiary-fixed": "#2a1700"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px" },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
